# Generated by Django 3.0.3 on 2020-02-03 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Room_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('adress1', models.CharField(max_length=250)),
                ('address2', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=9, unique=True)),
                ('mobile', models.CharField(max_length=12, unique=True)),
                ('room_number', models.PositiveIntegerField(unique=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.Room_type')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('number_of_rooms', models.PositiveIntegerField()),
                ('special_req', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('bed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.Bed_type')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.Client')),
            ],
        ),
    ]
