# Generated by Django 3.0.3 on 2020-02-06 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='adress1',
            new_name='address1',
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
