# Generated by Django 3.0.3 on 2020-02-11 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0004_auto_20200211_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='room_number',
        ),
    ]
